name: "Send SQS message"

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: List S3 buckets
        run: |
          aws s3 ls
