name: "Send SQS message"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: closed

jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - name: Populate "merged" variable
        run: |
          merged=$(jq .pull_request.merged "${GITHUB_EVENT_PATH}")
          echo "merged=$merged" >> $GITHUB_OUTPUT
        id: vars

      - name: Post PR closed event, if the close was a merge
        if: steps.vars.outputs.merged == 'true' && ! contains(github.event.pull_request.labels.*.name, 'skip-autoperf')
        run: |
          jq '.' "${GITHUB_EVENT_PATH}"
          aws sqs send-message --queue-url ${{ secrets.AWS_SQS_QUEUE_URL_AUTOPERF }} --message-group-id autoperf --message-body $(jq '.pull_request.merge_commit_sha' "${GITHUB_EVENT_PATH}" | sed 's/"//g')
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
