name: "Send SQS message"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: closed

jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: List S3 buckets
        run: |
          aws s3 ls

      - name: Populate "merged" variable
        run: |
          merged=$(jq .pull_request.merged "${GITHUB_EVENT_PATH}")
          echo "merged=$merged" >> $GITHUB_OUTPUT
        id: vars

      - name: Post PR closed event, if the close was a merge
        if: steps.vars.outputs.merged == 'true' && ! contains(github.event.pull_request.labels.*.name, 'skip-autoperf')
        run: |
          jq '.' "${GITHUB_EVENT_PATH}"
          aws sqs send-message --queue-url ${{ secrets.AWS_SQS_QUEUE_URL_AUTOPERF }} --message-group-id autoperf --message-body $(jq '.pull_request.merge_commit_sha' "${GITHUB_EVENT_PATH}" | sed 's/"//g')
